sbcl:
	sbcl --load "test-cairo-backend"

clisp:
	clisp -i test-cairo-backend.lisp

sbcl-x11:
	sbcl --load "test-x11-backend"

sbcl-svg:
	sbcl --load "test-svg-backend"

clisp-svg:
	clisp -i test-svg-backend.lisp

ecl-svg:
	/opt/common-lisp/bin/ecl -load test-svg-backend.lisp