
(in-package :cl-turtle-examples)

(defun c-curve-picture-01 ()
  (with-image ("pictures/rp-c-curve-01" :width 500 :height 400 :ext *ext*)
    (change-pen (new-pen :width 1 :color cl-colors:+darkblue+))
    (turn 90)
    (go-to -100 50)
    (pull-pen-down)
    (c-curve 200 12)
    (pull-pen-up)))

  
(defun sierpinski-triangle-picture-01 ()
  (with-image ("pictures/rp-sierpinski-triangle-01" :width 500 :height 400 :ext *ext*)
    (change-pen (new-pen :width 1 :color cl-colors:+darkblue+))
    (turn -90)
    (go-to 150 -150)
    (pull-pen-down)
    (sierpinski-triangle 300 7)
    (pull-pen-up)))

(defun snowflake-picture-01 ()
  (with-image ("pictures/rp-snowflake-01" :width 500 :height 400 :ext *ext*)
    (change-pen (new-pen :width 1 :color cl-colors:+darkblue+))
    (turn -90)
    (go-to 200 -150)
    (pull-pen-down)
    (snowflake 400 5)
    (pull-pen-up)))

(defun dragon-picture-01 ()
  (with-image ("pictures/rp-dragon-01" :width 500 :height 400 :ext *ext*)
    (change-pen (new-pen :width 1 :color cl-colors:+darkblue+))
    (turn -90)
    (go-to -50 -100)
    (pull-pen-down)
    (left-dragon 5 11)
    (pull-pen-up)))

(defun peano-picture-01 ()
  (with-image ("pictures/rp-peano-01" :width 500 :height 400 :ext *ext*)
    (change-pen (new-pen :width 1 :color cl-colors:+darkblue+))
    (turn -90)
    (go-to 100 100)
    (pull-pen-down)
    (peano 3 7)
    (pull-pen-up)))


(defun run-recursive ()
  (let ((*DEFAULT-PATHNAME-DEFAULTS* *examples-path*))
    (c-curve-picture-01)
    (sierpinski-triangle-picture-01)
    (snowflake-picture-01)
    (dragon-picture-01)
    (peano-picture-01)))

